script: |
            sudo rm -rf /usr/share/nginx/html/*
            sudo rm -rf /tmp/breakout-web
            cd /tmp
            git clone https://github.com/a28305/breakout-web.git
            sudo cp -r /tmp/breakout-web/* /usr/share/nginx/html/
            sudo chmod -R 755 /usr/share/nginx/html
            sudo systemctl restart nginx